### ISSUE TITLE
X-TIMESTAMP-MAP not supported

### ISSUE THREAD

**Issue by lukeselden** [plussub/srt-vtt-parser#9]
VTT used alongside HLS streams may have an additional `X-TIMESTAMP-MAP` line directly after the WEBVTT header line ([As per HLS spec](https://datatracker.ietf.org/doc/html/rfc8216#section-3.5)). This causes parsing to immediately fail because the code is looking for an ID or NOTE or STYLE.

Apparently the WebVTT allows for arbitrary [metadata header lines](https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/region.html#webvtt-region-metadata-header-syntax) after the initial `WEBVTT`, where the "region metadata header" must include a `:` and not include `-->`.

videojs/vtt.js uses a regex map for any lines with `:` while in the `HEADER` state ([code](https://github.com/videojs/vtt.js/blob/main/lib/parser/parser.js#L204))

Sample VTT:

```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:808300262,LOCAL:00:00:00.000

1
00:02:05.960 --> 00:03:07.292
The first line

2
00:03:07.293 --> 00:04:10.025
And next one
```

I can submit a PR if you'd like.

**Comment by ste-xx** [comment]
Hi,
your referenced spec is outdated. The [current](https://www.w3.org/TR/webvtt1) one does not metadata header lines. 
Anyway it should not break when a header is set. 
And it should not break if a region is defined. 
Thx for the feedback, I'm working on a fix.

**Comment by lukeselden** [comment]
I'm sure there's a more elegant way to handle this, but FWIW this is the pre-processing code I used as a workaround:

```ts
function sanitizeRawTranscript(raw: string) {
    const hasRegionMetadata = /^\s*WEBVTT[\r\n]+\S+:.+(?!=-->)\n/.test(raw);
    if (!hasRegionMetadata) return raw;
    // header is WEBVTT
    const [header, ...lines] = raw.split(/\r?\n/);
    // find first line that isn't a metadata header
    const skipHeadersStart = lines.findIndex(line => /^\S[^\:]*$|-->/.test(line));
    return [header, "\n", ...lines.slice(skipHeadersStart)].join("\n")
}
```
